services: 
    mongo:
        image: mongo:4.2
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
    app:
        build: .
        environment: 
            MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/mydb?authSource=admin
        ports:
            - "3000:3000"
        depends_on:
            - mongo
volumes:
    mongo-data:
